name = "go-learn"
main = "build/worker.mjs"
compatibility_date = "2026-06-22"

workers_dev = true

[[d1_databases]]
binding = "DB"
database_name = "go-learn-db"
database_id = "00b94b89-cb17-46e7-9afa-fe678a7e691b"

[assets]
directory = "web/static"
binding = "ASSETS"

[vars]
D1_DB_NAME = "DB"
