// Package content holds static lesson content compiled into the binary at
// build time. Generated by cmd/generate-content from the SQLite database.
// DO NOT EDIT — run `make generate-content` to regenerate.
package content

import (
	"html/template"

	"github.com/kartikkabadi/go-learn/internal/store"
)

// Lessons, Sections, Questions, Exercises, Glossary, References, Insights, Mission
// are populated by the generated file content_generated.go.

var Lessons []store.Lesson
var LessonsBySlug map[string]*store.Lesson
var LessonsByID map[string]*store.Lesson
var Sections map[string][]store.LessonSection
var Questions map[string][]store.Question
var QuestionsByID map[string]*store.Question
var Exercises []store.Exercise
var ExercisesByLesson map[string][]store.Exercise
var Glossary []store.GlossaryTerm
var References []store.Reference
var Insights []store.Insight
var Mission *store.Mission

// init is replaced by the generated file's init().
func init() {
	LessonsBySlug = map[string]*store.Lesson{}
	LessonsByID = map[string]*store.Lesson{}
	Sections = map[string][]store.LessonSection{}
	Questions = map[string][]store.Question{}
	QuestionsByID = map[string]*store.Question{}
	ExercisesByLesson = map[string][]store.Exercise{}
}

// _ keeps template import alive — generated code uses template.HTML.
var _ template.HTML
