// Command generate-content reads the SQLite database and emits a Go file
// with all static content as typed literals. Run via `make generate-content`.
package main

import (
	"database/sql"
	"fmt"
	"os"
	"strings"

	_ "modernc.org/sqlite"
)

func main() {
	dbPath := "progress/go-learn.db"
	if len(os.Args) > 1 {
		dbPath = os.Args[1]
	}
	db, err := sql.Open("sqlite", dbPath)
	if err != nil {
		fmt.Fprintf(os.Stderr, "open: %v\n", err)
		os.Exit(1)
	}
	defer db.Close()

	var b strings.Builder
	b.WriteString("// Code generated by cmd/generate-content. DO NOT EDIT.\n")
	b.WriteString("//go:build js && wasm\n\n")
	b.WriteString("package content\n\n")
	b.WriteString("import (\n")
	b.WriteString("\t\"html/template\"\n\n")
	b.WriteString("\t\"github.com/kartikkabadi/go-learn/internal/store\"\n")
	b.WriteString(")\n\n")
	b.WriteString("func init() {\n")

	emitLessons(&b, db)
	emitSections(&b, db)
	emitQuestions(&b, db)
	emitExercises(&b, db)
	emitGlossary(&b, db)
	emitReferences(&b, db)
	emitInsights(&b, db)
	emitMission(&b, db)

	b.WriteString("}\n")

	outPath := "internal/content/content_generated.go"
	if err := os.WriteFile(outPath, []byte(b.String()), 0o600); err != nil {
		fmt.Fprintf(os.Stderr, "write: %v\n", err)
		os.Exit(1)
	}
	fmt.Printf("generated %s (%d bytes)\n", outPath, b.Len())
}

func q(s string) string {
	return fmt.Sprintf("%q", s)
}

func emitLessons(b *strings.Builder, db *sql.DB) {
	rows, err := db.Query(`SELECT id, title, slug, summary, sort_order FROM lessons ORDER BY sort_order`)
	if err != nil {
		fmt.Fprintf(os.Stderr, "lessons: %v\n", err)
		os.Exit(1)
	}
	defer rows.Close()
	b.WriteString("\tLessons = []store.Lesson{\n")
	for rows.Next() {
		var l struct {
			ID, Title, Slug, Summary string
			SortOrder                int
		}
		if err := rows.Scan(&l.ID, &l.Title, &l.Slug, &l.Summary, &l.SortOrder); err != nil {
			fmt.Fprintf(os.Stderr, "scan lesson: %v\n", err)
			os.Exit(1)
		}
		fmt.Fprintf(b, "\t\t{ID: %s, Title: %s, Slug: %s, Summary: %s, SortOrder: %d},\n",
			q(l.ID), q(l.Title), q(l.Slug), q(l.Summary), l.SortOrder)
	}
	b.WriteString("\t}\n")
	b.WriteString("\tfor i := range Lessons {\n")
	b.WriteString("\t\tl := &Lessons[i]\n")
	b.WriteString("\t\tLessonsByID[l.ID] = l\n")
	b.WriteString("\t\tif l.Slug != \"\" {\n")
	b.WriteString("\t\t\tLessonsBySlug[l.Slug] = l\n")
	b.WriteString("\t\t}\n")
	b.WriteString("\t}\n\n")
}

func emitSections(b *strings.Builder, db *sql.DB) {
	rows, err := db.Query(`SELECT id, lesson_id, heading, body_html, sort_order FROM lesson_sections ORDER BY lesson_id, sort_order`)
	if err != nil {
		fmt.Fprintf(os.Stderr, "sections: %v\n", err)
		os.Exit(1)
	}
	defer rows.Close()
	b.WriteString("\t{\n")
	for rows.Next() {
		var s struct {
			ID, LessonID, Heading, BodyHTML string
			SortOrder                       int
		}
		if err := rows.Scan(&s.ID, &s.LessonID, &s.Heading, &s.BodyHTML, &s.SortOrder); err != nil {
			fmt.Fprintf(os.Stderr, "scan section: %v\n", err)
			os.Exit(1)
		}
		fmt.Fprintf(b, "\t\tSections[%s] = append(Sections[%s], store.LessonSection{ID: %s, LessonID: %s, Heading: %s, BodyHTML: template.HTML(%s), SortOrder: %d})\n",
			q(s.LessonID), q(s.LessonID), q(s.ID), q(s.LessonID), q(s.Heading), q(s.BodyHTML), s.SortOrder)
	}
	b.WriteString("\t}\n\n")
}

func emitQuestions(b *strings.Builder, db *sql.DB) {
	// Load questions with options via a join, ordered so options follow their question.
	rows, err := db.Query(`
		SELECT q.id, q.lesson_id, q.prompt, q.correct_key, q.question_type, q.section_tag, q.sort_order,
			o.question_id, o.option_key, o.label, o.is_correct, o.sort_order
		FROM questions q
		LEFT JOIN question_options o ON o.question_id = q.id
		ORDER BY q.lesson_id, q.sort_order, o.sort_order
	`)
	if err != nil {
		fmt.Fprintf(os.Stderr, "questions: %v\n", err)
		os.Exit(1)
	}
	defer rows.Close()

	b.WriteString("\t{\n")
	b.WriteString("\t\tqIdx := map[string]int{}\n")
	for rows.Next() {
		var row struct {
			ID, LessonID, Prompt, CorrectKey, QuestionType, SectionTag string
			SortOrder                                                  int
			OptQID, OptKey, OptLabel                                   sql.NullString
			OptCorrect                                                 sql.NullInt64
			OptOrder                                                   sql.NullInt64
		}
		if err := rows.Scan(
			&row.ID, &row.LessonID, &row.Prompt, &row.CorrectKey, &row.QuestionType, &row.SectionTag, &row.SortOrder,
			&row.OptQID, &row.OptKey, &row.OptLabel, &row.OptCorrect, &row.OptOrder,
		); err != nil {
			fmt.Fprintf(os.Stderr, "scan question: %v\n", err)
			os.Exit(1)
		}
		fmt.Fprintf(b, "\t\tif len(Questions[%s]) == 0 || Questions[%s][len(Questions[%s])-1].ID != %s {\n",
			q(row.LessonID), q(row.LessonID), q(row.LessonID), q(row.ID))
		fmt.Fprintf(b, "\t\t\tQuestions[%s] = append(Questions[%s], store.Question{ID: %s, LessonID: %s, Prompt: %s, CorrectKey: %s, QuestionType: %s, SectionTag: %s, SortOrder: %d})\n",
			q(row.LessonID), q(row.LessonID), q(row.ID), q(row.LessonID), q(row.Prompt), q(row.CorrectKey), q(row.QuestionType), q(row.SectionTag), row.SortOrder)
		fmt.Fprintf(b, "\t\t\tqIdx[%s] = len(Questions[%s]) - 1\n", q(row.ID), q(row.LessonID))
		fmt.Fprintf(b, "\t\t\tQuestionsByID[%s] = &Questions[%s][qIdx[%s]]\n", q(row.ID), q(row.LessonID), q(row.ID))
		b.WriteString("\t\t}\n")
		if row.OptQID.Valid {
			fmt.Fprintf(b, "\t\tQuestions[%s][qIdx[%s]].Options = append(Questions[%s][qIdx[%s]].Options, store.QuestionOption{QuestionID: %s, OptionKey: %s, Label: %s, IsCorrect: %t, SortOrder: %d})\n",
				q(row.LessonID), q(row.ID), q(row.LessonID), q(row.ID),
				q(row.OptQID.String), q(row.OptKey.String), q(row.OptLabel.String), row.OptCorrect.Int64 == 1, int(row.OptOrder.Int64))
		}
	}
	b.WriteString("\t}\n\n")
}

func emitExercises(b *strings.Builder, db *sql.DB) {
	rows, err := db.Query(`SELECT id, lesson_id, title, path, instructions, sort_order FROM exercises ORDER BY sort_order`)
	if err != nil {
		fmt.Fprintf(os.Stderr, "exercises: %v\n", err)
		os.Exit(1)
	}
	defer rows.Close()
	b.WriteString("\tExercises = []store.Exercise{\n")
	for rows.Next() {
		var e struct {
			ID, LessonID, Title, Path, Instructions string
			SortOrder                               int
		}
		if err := rows.Scan(&e.ID, &e.LessonID, &e.Title, &e.Path, &e.Instructions, &e.SortOrder); err != nil {
			fmt.Fprintf(os.Stderr, "scan exercise: %v\n", err)
			os.Exit(1)
		}
		fmt.Fprintf(b, "\t\t{ID: %s, LessonID: %s, Title: %s, Path: %s, Instructions: %s, SortOrder: %d},\n",
			q(e.ID), q(e.LessonID), q(e.Title), q(e.Path), q(e.Instructions), e.SortOrder)
	}
	b.WriteString("\t}\n")
	b.WriteString("\tfor i := range Exercises {\n")
	b.WriteString("\t\tExercisesByLesson[Exercises[i].LessonID] = append(ExercisesByLesson[Exercises[i].LessonID], Exercises[i])\n")
	b.WriteString("\t}\n\n")
}

func emitGlossary(b *strings.Builder, db *sql.DB) {
	rows, err := db.Query(`SELECT id, term, definition, sort_order FROM glossary_terms ORDER BY sort_order`)
	if err != nil {
		fmt.Fprintf(os.Stderr, "glossary: %v\n", err)
		os.Exit(1)
	}
	defer rows.Close()
	b.WriteString("\tGlossary = []store.GlossaryTerm{\n")
	for rows.Next() {
		var g struct {
			ID, Term, Definition string
			SortOrder            int
		}
		if err := rows.Scan(&g.ID, &g.Term, &g.Definition, &g.SortOrder); err != nil {
			fmt.Fprintf(os.Stderr, "scan glossary: %v\n", err)
			os.Exit(1)
		}
		fmt.Fprintf(b, "\t\t{ID: %s, Term: %s, Definition: %s, SortOrder: %d},\n",
			q(g.ID), q(g.Term), q(g.Definition), g.SortOrder)
	}
	b.WriteString("\t}\n\n")
}

func emitReferences(b *strings.Builder, db *sql.DB) {
	rows, err := db.Query(`SELECT id, title, url, notes, COALESCE(lesson_id, '') FROM references_ext ORDER BY title`)
	if err != nil {
		fmt.Fprintf(os.Stderr, "references: %v\n", err)
		os.Exit(1)
	}
	defer rows.Close()
	b.WriteString("\tReferences = []store.Reference{\n")
	for rows.Next() {
		var r struct {
			ID, Title, URL, Notes, LessonID string
		}
		if err := rows.Scan(&r.ID, &r.Title, &r.URL, &r.Notes, &r.LessonID); err != nil {
			fmt.Fprintf(os.Stderr, "scan reference: %v\n", err)
			os.Exit(1)
		}
		fmt.Fprintf(b, "\t\t{ID: %s, Title: %s, URL: %s, Notes: %s, LessonID: %s},\n",
			q(r.ID), q(r.Title), q(r.URL), q(r.Notes), q(r.LessonID))
	}
	b.WriteString("\t}\n\n")
}

func emitInsights(b *strings.Builder, db *sql.DB) {
	rows, err := db.Query(`SELECT id, title, body, kind, active, created_at FROM insights WHERE active = 1 ORDER BY created_at`)
	if err != nil {
		fmt.Fprintf(os.Stderr, "insights: %v\n", err)
		os.Exit(1)
	}
	defer rows.Close()
	b.WriteString("\tInsights = []store.Insight{\n")
	for rows.Next() {
		var ins struct {
			ID, Title, Body, Kind, CreatedAt string
			Active                           int
		}
		if err := rows.Scan(&ins.ID, &ins.Title, &ins.Body, &ins.Kind, &ins.Active, &ins.CreatedAt); err != nil {
			fmt.Fprintf(os.Stderr, "scan insight: %v\n", err)
			os.Exit(1)
		}
		fmt.Fprintf(b, "\t\t{ID: %s, Title: %s, Body: %s, Kind: %s, Active: %t, CreatedAt: %s},\n",
			q(ins.ID), q(ins.Title), q(ins.Body), q(ins.Kind), ins.Active == 1, q(ins.CreatedAt))
	}
	b.WriteString("\t}\n\n")
}

func emitMission(b *strings.Builder, db *sql.DB) {
	var m struct {
		Why, SuccessCriteria, ConstraintsText string
	}
	err := db.QueryRow(`SELECT why, success_criteria, constraints_text FROM mission WHERE id = 1`).Scan(
		&m.Why, &m.SuccessCriteria, &m.ConstraintsText,
	)
	if err == sql.ErrNoRows {
		b.WriteString("\tMission = nil\n\n")
		return
	}
	if err != nil {
		fmt.Fprintf(os.Stderr, "mission: %v\n", err)
		os.Exit(1)
	}
	fmt.Fprintf(b, "\tMission = &store.Mission{Why: %s, SuccessCriteria: %s, ConstraintsText: %s}\n\n",
		q(m.Why), q(m.SuccessCriteria), q(m.ConstraintsText))
}
